import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Container from "./components/container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const classBody = "min-h-screen bg-background font-sans antialiased bg-zinc-100 " + inter.className; 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={classBody}>
        <Header />
        <main>
          <Container className="py-5">
            {children}
          </Container>
        </main>
      </body>
    </html>
  );
}
